package com.ch2.string;

/**
 * Print all subsequences of a string
 *
 * Difficulty Level : Medium
 * Last Updated : 18 Jul, 2022
 * Given a string, we have to find out all subsequences of it. A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.
 *
 * Examples:
 *
 * Input : abc
 * Output : a, b, c, ab, bc, ac, abc
 *
 * Input : aaa
 * Output : a, aa, aaa
 */
public class SubsequenceString {
}
